# Generated by Django 4.0.3 on 2022-04-19 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_notes_tag_task_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
